config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolios_show'
  get 'guides/book'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
    <div class="inner">
      <h3 class="masthead-brand">JBjohnnyboy's Website</h3>
      <nav class="nav nav-masthead">
        <%= link_to "Home", root_path, class: 'nav-link' %>
        <%= link_to "About Me", about_me_path, class: 'nav-link' %>
        <%= link_to "Contact", contact_path, class: 'nav-link' %>
        <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
        <%= link_to "Portfolios", portfolios_path, class: 'nav-link' %>
        <%= login_helper 'nav-link' %>
      </nav>
    </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Me", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
 <div class="col-sm-4 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://www.youtube.com/channel/UC9MUanAfzsZv85oif_CgBGA"><%= fa_icon "youtube-play"%> Youtube</a></li>
      <li><a href="https://twitter.com/bounding_C?lang=en"><%= fa_icon "twitter-square"%> Twitter</a></li>
      <li><a href="https://jbjohnnyboy.tumblr.com/"><%= fa_icon "tumblr-square"%> Tumblr</a></li>
      <li><a href="http://jbjohnnyboy.deviantart.com/"><%= fa_icon "deviantart"%> DeviantArt</a></li>
      <li><a href="https://github.com/JBjohnnyboy"><%= fa_icon "github-alt"%> Github</a></li>
      
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
  <div class="<%= location %>">
    <%= link_to "Home", root_path %>
    <%= link_to "About Me", about_me_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "Blogs", blogs_path %>
    <%= link_to "Portfolios", portfolios_path %>
    <%= login_helper %>
 </div>